---
- hosts: all
  become: true
  vars:
      packages:
        - name: zeek
          required: True
        - name: suricata
          required: True
        - name: net-tools
          required: True
  tasks:
    - name: Install security tools on Debian systems
      apt:
         name: Debian
         state: latest
         update_cache: yes
      loop: '{{ packages }}'
      when: item.required == True
      when: ansible_os_family == 'Debian'

    - name: Install security tools on RedHat systems
      yum:
         name: Red Hat
         state: latest
         update_cache: yes
      with_items: '{{ packages }}'
      when: item.required == True
      when: ansible_os_family == 'Red Hat'
