---
- hosts: all
  tasks:
  
    - name: Install SELinux Required Packages
      yum:
        name:
          - "python3-libselinux"
          - "policycoreutils-python-utils"

    - name: Enforcing SELinux
      ansible.posix.selinux:
       policy: targeted
       state: enforcing


    - name: Set SELinux to Permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive
