---
- hosts: all
  tasks:

    - name: Enable SELinux
      ansible.posix.selinux:
       state: enabled


    - name: Set SELinux to Permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive
