---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache, ensure Vim is installed on all Debian systems
      apt:
        name: vim
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt cache, ensure Vim is installed on all RedHat systems
      yum:
        name: vim
        update_cache: yes
      when: ansible_facts['os_family'] == "Red Hat"
