---
- hosts: all
  become: true
  become_method: enable

  tasks:

    ######## Download Splunk UF

    - name: Download the latest Splunk Forwarder RPM
      ansible.builtin.get_url:
              url: "https://download.splunk.com/products/universalforwarder/releases/9.0.3/linux/splunkforwarder-9.0.3-dd0128b1f8cd-Linux-x86_64.tgz"
              dest: /tmp
              mode: 0644
              register: splunk_uf_tgz

    - name: Unarchive the file
      ansible.builtin.unarchive:
              src: "https://download.splunk.com/products/universalforwarder/releases/9.0.3/linux/splunkforwarder-9.0.3-dd0128b1f8cd-Linux-x86_64.tgz"
              dest: /tmp

    ####### Verify MD5 Hash

    - name: Get tgz filename and version number
      set_fact: 
        splunk_uf_tgz_filename: "{{ splunk_uf_downloaded_tgz.dest | regex_search('(splunkforwarder-.+-Linux-x86_64.tgz)') }}"
        splunk_uf_tgz_version: "{{ splunk_uf_downloaded_tgz.dest | regex_findall('splunkforwarder-([0-9.]+)') }}"

    - name: Install Splunk Forwarder on Debian nodes
      apt:
          state: present
          update_cache: yes
          when: item.required == True
          when: ansible_os_family == "Debian"

    - name: Install Splunk Forwarder on RedHat nodes
      yum:
          state: present
          update_cache: yes
          when: item.required == True
          when: ansible_os_family == "RedHat"

    - name: Download and insert props.conf template
      ansible.builtin.get_url:
              url: "https://github.com/wazuh/wazuh/blob/master/extensions/splunk/props.conf"
              dest: /tmp


    - name: Download and insert inputs.conf template
      ansible.builtin.get_url:
              url: "https://github.com/wazuh/wazuh/blob/master/extensions/splunk/inputs.conf"
              dest: /tmp

    - name: Point Forwarder output to Splunk's Indexer <INDEXER-IP>:<INDEXER-PORT>
      command: /tmp/bin/splunk add forward-server 142.93.249.160:8000
