---
- hosts: all
  become: true
  vars_files: 
   - se_pkg.yml

  tasks:

   - name: Installing SELinux dependencies on Ubuntu
     apt:
         update_cache: yes
     with_items: '{{ packages }}'
     when: ansible_os_family == 'Debian'


   - name: Installing SELinux dependencies on CentOS
     yum:
         update_cache: yes
     with_items: '{{ packages }}'
     when: ansible_os_family == 'RedHat'
