---
- hosts: all
  become: true
  vars:
    - se_pkg.yml

  tasks:
   - name: Installing SELinux dependencies on Ubuntu
     apt:
         name: Debian
         state: latest
         update_cache: yes
     with_items: '{{ packages }}'
     when: item.required == True
     when: ansible_os_family == 'Ubuntu'


   - name: Installing SELinux dependencies on CentOS
     yum:
         name: Red Hat
         state: latest
         update_cache: yes
     with_items: '{{ packages }}'
     when: item.required == True
     when: ansible_os_family == 'CentOS'
