---
- hosts: all
  tasks:
 

    - name: Enforcing SELinux
      ansible.posix.selinux:
       policy: targeted
       state: enforcing


    - name: Set SELinux to Permissive mode
      ansible.posix.selinux:
        policy: targeted
        state: permissive
