---
- name: Create user on Ubuntu
  hosts: remote-server
  become: yes
  gather_facts: false
  vars:
    - users.yaml
  tasks:
   
      - name: Adding security group
        group:
          name: Security
          state: present
          
      - name: Create users and add them to the security group\
        user:
          name: "{{item.name}}"
          create_home: yes
          password: "{{ 'password' | password_hash('sha512') }}"
          update_password: on_create
          groups: security
        with_items: "{{ users }}"
    
      #- name: Add {{ user }} to sudoers file
       # ansible.builtin.lineinfile:
        #  path: /etc/sudoers
         # regexp: '^{{ user }}'
          #line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
          #validate: 'visudo -cf %s'
          
      - name: Allow public key authentication
        ansible.builtin.lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^(#)?PubkeyAuthentication \w*$'
          line: 'PubkeyAuthentication yes'
          state: present
          
      - name: Create SSH directory if it does not exist
        ansible.builtin.file:
          path: '~/.ssh/'
          state: directory
          mode: '0600'

      - name: Add public key to authorized_keys
        authorized_key:
          user: "{{ user }}"
          state: present
          key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

      - name: Deny root from logging in
        ansible.builtin.lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^(#)?PermitRootLogin \w*$'
          line: 'PermitRootLogin no'
          state: present

      - name: Allow specific users to log in
        ansible.builtin.lineinfile:
          dest: /etc/ssh/sshd_config
          regexp: '^AllowUsers'
          line: 'AllowUsers {{ user }}'
          state: present
