---
- hosts: all
  become: true
  tasks:
    - name: On all Debian flavors, update cache and make sure Vim is installed
      apt:
        name: vim
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
