---
- hosts: all
  become: yes
  tasks:
    - name: Ubuntu: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip
      when: ansible_facts['os_family'] == "Debian"
      
    - name: Centos: Update apt cache and make sure Vim, Curl and Unzip are installed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - curl
        - unzip 
      when: ansible_facts['os_family'] == "Debian"
