---
- hosts: all
  become: true
  tasks:
    - name: Update cache, ensure Vim is installed on Debian systems
      apt:
        name: vim
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update cache, ensure Vim is installed on Red Hat systems
      yum:
        name: vim
        update_cache: yes
      when: ansible_facts['os_family'] == "Red Hat"
